version: "4.28.0"
services:

  java_app:
    container_name: java_mdbapp
    image: crud-mdb:1.0
    build: .
    ports:
      - 8080:8080
    depends_on:
      - java_db
  java_db:
    container_name: java_mdb
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: contrasena
      MYSQL_DATABASE: mariadb01
